## Esercizi sui Numpy array  7 Marzo 2023


In [54]:
import numpy as np

- **0.** Costruisci un numpy array con 2000000 elementi equidistanti nell'intervallo [0,4] utilizzando il linspace e con il metodo che assegna i valori in un ciclo dopo aver definito il passo e confronta il tempo di esecuzione delle due modalità di costruzione.

In [55]:
n = 2000000
B=np.linspace(0,4,n)


- **1.**  Costruire un numpy array 1d, denominato  `c`, di valori equidistanti che variano tra 7 e 41 con step 2 e trasformarlo in un numpy array 2d, denominato `C1` , con shape(2,9) applicando il metodo `.reshape((m,n))` a c. 

  Si tratta di una copia o di una `vista dell'array originale` con una nuova shape, con dati condivisi con l'array originale?


In [56]:
c = np.arange(7, 42, 2)
print(c)
c1 = c.reshape(2,9)
print(c)
print(c1)

[ 7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41]
[ 7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41]
[[ 7  9 11 13 15 17 19 21 23]
 [25 27 29 31 33 35 37 39 41]]


Importa il modulo numpy

 - **2.** Costruire un numpy array 1d, denominato $C$ di valori che variano tra 15 e 41 con step 2 e trasformarlo in un numpy array 2d con shape(7,2) usando il metodo .`resize(7,2)` che lavora in-place,  (cioè  modifica l'array esistente, senza creare una copia). Verificare la shape di C

In [57]:
C = np.arange(15, 41, 2)
C.resize((7,2))
print(C)

[[15 17]
 [19 21]
 [23 25]
 [27 29]
 [31 33]
 [35 37]
 [39  0]]


- **3.** Costruire un numpy array 1d $c$ di valori che variano tra 15 e 41 con step 2 e trasformarlo in un numpy array 2d con shape(7,2) usando la funzione `reshape`. Verificare se la funzione  `reshape` restituisce una copia oppure una vista. 

- **4.** Costruire un numpy array 1d $d$ di valori che variano tra 15 e 41 con step 2 e trasformarlo in un numpy array 2d con shape(7,2) usando la funzione `resize`. Verificare se la funzione  `resize` restituisce una copia oppure una vista. 

- **5.** Dato il numpy array s formato da 100 valori equidistanti in  [0,4], considerarne il reshape in un array 2d che ha 4 righe con un numero opportuno di colonne

In [58]:
s = np.linspace(0,4,100)
s1 = s.reshape((4,-1))
#uguale
#s2 =  s.reshape((4,25))
print(s1)

[[0.         0.04040404 0.08080808 0.12121212 0.16161616 0.2020202
  0.24242424 0.28282828 0.32323232 0.36363636 0.4040404  0.44444444
  0.48484848 0.52525253 0.56565657 0.60606061 0.64646465 0.68686869
  0.72727273 0.76767677 0.80808081 0.84848485 0.88888889 0.92929293
  0.96969697]
 [1.01010101 1.05050505 1.09090909 1.13131313 1.17171717 1.21212121
  1.25252525 1.29292929 1.33333333 1.37373737 1.41414141 1.45454545
  1.49494949 1.53535354 1.57575758 1.61616162 1.65656566 1.6969697
  1.73737374 1.77777778 1.81818182 1.85858586 1.8989899  1.93939394
  1.97979798]
 [2.02020202 2.06060606 2.1010101  2.14141414 2.18181818 2.22222222
  2.26262626 2.3030303  2.34343434 2.38383838 2.42424242 2.46464646
  2.50505051 2.54545455 2.58585859 2.62626263 2.66666667 2.70707071
  2.74747475 2.78787879 2.82828283 2.86868687 2.90909091 2.94949495
  2.98989899]
 [3.03030303 3.07070707 3.11111111 3.15151515 3.19191919 3.23232323
  3.27272727 3.31313131 3.35353535 3.39393939 3.43434343 3.47474747
  3.5151

- **6.** Dato il numpy array s formato da 100 valori equidistanti in  [0,4], considerarne il reshape in un array 2d che ha 4 colonne con un numero opportuno di righe

In [59]:
s3 = s.reshape((-1,4))
print(s3)

[[0.         0.04040404 0.08080808 0.12121212]
 [0.16161616 0.2020202  0.24242424 0.28282828]
 [0.32323232 0.36363636 0.4040404  0.44444444]
 [0.48484848 0.52525253 0.56565657 0.60606061]
 [0.64646465 0.68686869 0.72727273 0.76767677]
 [0.80808081 0.84848485 0.88888889 0.92929293]
 [0.96969697 1.01010101 1.05050505 1.09090909]
 [1.13131313 1.17171717 1.21212121 1.25252525]
 [1.29292929 1.33333333 1.37373737 1.41414141]
 [1.45454545 1.49494949 1.53535354 1.57575758]
 [1.61616162 1.65656566 1.6969697  1.73737374]
 [1.77777778 1.81818182 1.85858586 1.8989899 ]
 [1.93939394 1.97979798 2.02020202 2.06060606]
 [2.1010101  2.14141414 2.18181818 2.22222222]
 [2.26262626 2.3030303  2.34343434 2.38383838]
 [2.42424242 2.46464646 2.50505051 2.54545455]
 [2.58585859 2.62626263 2.66666667 2.70707071]
 [2.74747475 2.78787879 2.82828283 2.86868687]
 [2.90909091 2.94949495 2.98989899 3.03030303]
 [3.07070707 3.11111111 3.15151515 3.19191919]
 [3.23232323 3.27272727 3.31313131 3.35353535]
 [3.39393939 

 - **7.** Scrivere il numpy  array 2d [[10,11,12],[13,14,15],[16,17,18]] e trasformarlo in un numpy array 1d usando i metodi `.ravel()` e `.flatten()`. Verificare che flatten restituisce una copia mentre ravel restituisce una vista.

In [60]:
a=np.arange(10,19,1).reshape((3,3))
a1 = a.ravel()
a1.flags['OWNDATA']

False

In [61]:
a2 = a.flatten()
a2.flags['OWNDATA']

True

 - **8.** creare i due  numpy array 1d
f1= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] ed 
f2= [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
"vederli" come matrici  4x4 ed effettuarne il prodotto scalare, memorizzando in f3 la matrice che nasce dal loro prodotto.

In [62]:
f1= np.arange(0,16).reshape((4,4))
f2 =np.arange(16,32).reshape((4,4))
print(f1)
print(f2)
f3 = np.dot(f1,f2)
print(f3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 152  158  164  170]
 [ 504  526  548  570]
 [ 856  894  932  970]
 [1208 1262 1316 1370]]


- **9.**                Dati :
 - Numpy Array A di shape (2,10) : array di valori random campionati da una distribuzione gaussiana con media 0 e varianza 1.
 - Numpy array 1D B di shape (20,) formato dagli interi da 0 a 19.
 
"Vedere" A come un array 1D di 20 elementi ed effettuare la somma di A+B



 - **10.** Creare un array 2D di shape (5,5), denominato B2, con valori tutti uguali a 15.
Creare una copia B3 di B2. Modificare l'elemento B3[0,0] assegnandogli il valore 150. 
Stampare il numpy array B2 ed il numpy array B3 e verificare che B2, dopo la modifica di B3, è rimasto inalterato

 - **11.** - Dato un numpy array 1D, di shape (10,) denominato `f`, costituito da 10 valori equidistanti nell'intervallo [0,1], aumentarne la dimensionalità, in maniera tale che abbia shape (10,1)

In [63]:
f=np.linspace(0,1,10)
f1=f.reshape(10,1)

- **12.** Dati i seguenti numpy array
  - a= np.array([14,13,12,11])
  - b=np.array([[4,3,2,1],[9,10,11,12]])

  Costruire il numpy array che si ottiene concatenando a e b per righe


In [64]:
a= np.array([14,13,12,11])
b=np.array([[4,3,2,1],[9,10,11,12]])
c=np.concatenate((a.reshape(1,4),b),axis=0)
print(c)

[[14 13 12 11]
 [ 4  3  2  1]
 [ 9 10 11 12]]


- **13.** - Dati i seguenti numpy array
  - a= np.array([14,13,12,11])
  - b=np.array([[4,3,2,1],[9,10,11,12],[4,3,2,1],[9,10,11,12]])

  Costruire il numpy array che si ottiene concatenando a e b per colonne

In [65]:
a= np.array([14,13,12,11])
b=np.array([[4,3,2,1],[9,10,11,12],[4,3,2,1],[9,10,11,12]])
c = np.concatenate((a.reshape(4,1),b), axis=1)


- **14.** Costruisci la matrice tridiagonale A di ordine 10, che ha elementi diagonali $A_{i,i}=10$, i=1,20, elementi nella codiagonale inferiore $A_{i-1,i}=-12$ i=2,..,20
elementi nella codiagonale superiore $A_{i,i+1}=-2$ i=1,..,19

In [66]:
d = np.ones((20,))*10
i = np.ones((19,))*-12
s = np.ones((19))*-2

A=np.diag(d)+np.diag(i,-1)+np.diag(s,1)
print(A)

[[ 10.  -2.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [-12.  10.  -2.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0. -12.  10.  -2.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0. -12.  10.  -2.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. -12.  10.  -2.   0.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0. -12.  10.  -2.   0.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. -12.  10.  -2.   0.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0. -12.  10.  -2.   0.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0. -12.  10.  -2.   0.   0.   0.   0.
    0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. -12.  10.  -2

 - **15** Costruire la matrice identità della stessa dimensione di A

In [67]:
I = np.eye(A.shape[0])
print(I)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.

- **16.** Selezionare dalla matrice A le righe che vanno dalla 2 alla 9 con step 2 e le colonne che vanno dalla 3 alla 6 con step 2


In [68]:
A1=A[2:10:2,3:7:2]
print(A1)

[[ -2.   0.]
 [-12.  -2.]
 [  0. -12.]
 [  0.   0.]]


- **17.** A1 è una vista di A, come trasformarla in copia?

In [73]:
A1.flags['OWNDATA']
A1=A[2:10:2,3:7:2].copy()
A1.flags['OWNDATA']

True

- **18.** Costruisci due numpy array di shape (5,5) 
   - A formata da numeri interi casuali  nell'intervallo [1,20]
   - B formata da numeri interi casuali  nell'intervallo [1,6]
 
  Costruisci in modalità element-wise le matrici
  C=A+B
  D=A-B
  E=A*B
  F=A\B

- **19.** Costruisci il prodotto scalare tra le  matrici A e B (righe per colonne)

- **20.** Somma gli elementi delle righe della matrice B

- **21.** Somma gli elementi delle colonne della matrice B

- **22.** Somma tutti gli elementi di B

- **23.** Calcolare il minimo degli elementi di B, tra le righe, tra le colonne, il minimo di tutta la matrice B

- **24** Calcola, memorizzando in un vettore, la somma degli elementi di ogni colonna di $ |B |$. Calcola successivamente il massimo di questo vettore.
$cmaxc= \max_{j=1,n} \sum_{i} |b_{ij}|$

- **25.** Calcola, memorizzando in un vettore, la somma degli elementi di ogni riga  di $ |B |$. Calcola successivamente il massimo di questo vettore.
$cmaxr= \max_{i=1,n} \sum_{j} |b_{ij}|$

- **26.** Effettua nella matrice B lo scambio tra la  riga 2 e  la riga 3

 - **27.** Calcola il valore massimo della colonna 0-esima della matrice B e l'indice di riga a cui appartiene

- **28.** Scrivi una funzione border(m,n) per creare un array 2D di shape(m,n) che abbia tutti valori zero, ad eccezione degli elementi attorno al bordo (ovvero la prima e l'ultima riga e la prima e l'ultima colonna), che deve avere un valore pari a uno. Prevedi un argomento di default che se impostato a True visualizza la matrice 

- **29.** Scrivi una funzione `visualizza(f,a,b)`che prende in input una lambda function, gli estremi dell'intervallo su cui è definita e la visualizzi in una finestra grafica

- **30.** Scrivi una funzione `visualizza2(f,a,b,f2,a2,b2)`che prende in input una lambda function f e gli estremi dell'intervallo su cui è definita, una lambda function f2 e gli estremi dell'intervallo su cui è definita, e l2 visualizzi sulla stessa finestra grafica

- 